### ISSUE TITLE
Build with fontmake

### ISSUE THREAD

**Issue by davelab6** [mjlagattuta/Hepta-Slab#7]
While https://github.com/mjlagattuta/Hepta-Slab/issues/1 can be postponed, I'm filing this issue to call out one of the key steps along the way to that - building the project successfully with http://github.com/googlei18n/fontmake/ :)

Ideally this can be scripted with a `/sources/build.py` (or even a `build.sh` given that it can be a one-shot command line :) 

However, fontmake is still somewhat basic and doesn't support the export filters that GlyphsApp itself does, so if you use those, then we'll have to postpone this... But it will make @m4rc1e happy -- beyond this project passing fontbakery checks, which I'll file separately now :)

**Comment by mjlagattuta** [comment]
Due to the bracket layers on this project I had to export the VF from glyphs but have taken steps to get it production-ready. In the future once fontmake supports bracket layers in Glyph App I can rebuild the binary with that.

Though the VF export from glyphs is still in Beta I believe the post-export steps I have taken have addressed these issues, it currently passes fontbakery, (1 fail since it couldn't find the license file), see #8 

All the tools for generating the binary VF are available, but I will also be adding a BUILD.md to clarify the process

**Comment by davelab6** [comment]
Closing as there are build scripts in https://github.com/mjlagattuta/Hepta-Slab/blob/master/sources/tools/
